//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempConverterClient.TempConversionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempConversionService.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoF", ReplyAction="*")]
        float CtoF(float c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoF", ReplyAction="*")]
        System.Threading.Tasks.Task<float> CtoFAsync(float c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoC", ReplyAction="*")]
        float FtoC(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<float> FtoCAsync(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoK", ReplyAction="*")]
        float CtoK(float c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoK", ReplyAction="*")]
        System.Threading.Tasks.Task<float> CtoKAsync(float c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KtoC", ReplyAction="*")]
        float KtoC(float k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<float> KtoCAsync(float k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoK", ReplyAction="*")]
        float FtoK(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoK", ReplyAction="*")]
        System.Threading.Tasks.Task<float> FtoKAsync(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KtoF", ReplyAction="*")]
        float KtoF(float k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KtoF", ReplyAction="*")]
        System.Threading.Tasks.Task<float> KtoFAsync(float k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TempConverterClient.TempConversionService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TempConverterClient.TempConversionService.WebService1Soap>, TempConverterClient.TempConversionService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float CtoF(float c) {
            return base.Channel.CtoF(c);
        }
        
        public System.Threading.Tasks.Task<float> CtoFAsync(float c) {
            return base.Channel.CtoFAsync(c);
        }
        
        public float FtoC(float f) {
            return base.Channel.FtoC(f);
        }
        
        public System.Threading.Tasks.Task<float> FtoCAsync(float f) {
            return base.Channel.FtoCAsync(f);
        }
        
        public float CtoK(float c) {
            return base.Channel.CtoK(c);
        }
        
        public System.Threading.Tasks.Task<float> CtoKAsync(float c) {
            return base.Channel.CtoKAsync(c);
        }
        
        public float KtoC(float k) {
            return base.Channel.KtoC(k);
        }
        
        public System.Threading.Tasks.Task<float> KtoCAsync(float k) {
            return base.Channel.KtoCAsync(k);
        }
        
        public float FtoK(float f) {
            return base.Channel.FtoK(f);
        }
        
        public System.Threading.Tasks.Task<float> FtoKAsync(float f) {
            return base.Channel.FtoKAsync(f);
        }
        
        public float KtoF(float k) {
            return base.Channel.KtoF(k);
        }
        
        public System.Threading.Tasks.Task<float> KtoFAsync(float k) {
            return base.Channel.KtoFAsync(k);
        }
    }
}
